CREATE TABLE USER (
  ID       NUMBER(22) PRIMARY KEY,
  USERNAME VARCHAR2(60) NOT NULL,
  PASSWORD VARCHAR2(60) NOT NULL
);

CREATE SEQUENCE "USER_SEQ" MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 CACHE 5;

INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES (USER_SEQ.NEXTVAL, 'admin', 'password');

